### PR TITLE
Dark themes

### PR DESCRIPTION
**Pull request by g2asell2019**
After tweaking your UI, I chose the default avalonia dark theme

There is one small problem, I couldn't find where to change those 3 headers background
image

### CODE REVIEW

**Comment by PMahern** [comment]
It looks great. The header control has a style being applied in [Styles/Styles.xml](https://github.com/PMahern/StableDiffusionTagManager/blob/041c73d93129266473cd2f4809217b768dd173c8/src/StableDiffusionTagManager/Styles/Styles.axaml) It's currently using SystemAltMediumLowColor for the background of the header and the border.

**Comment by PMahern** [comment]
I did pull up a dialog that's using the header control and the label color for the theme is clashing with the hard coded color in the control.

image

**Comment by PMahern** [comment]
Also at the bottom of the image viewer in the main window is a label that displays the filename, looks like that's also clashing (probably a hard coded background color again).

image

**Comment by g2asell2019** [comment]
Default:
image

Open project:
image

Project settings:
image

**Comment by g2asell2019** [comment]
I removed some hard-coded colors https://github.com/PMahern/StableDiffusionTagManager/pull/1/commits/85a39f86ee499baf528852c0b1077d33534df43b.

Still have to retain this to make background color more fluent https://github.com/PMahern/StableDiffusionTagManager/pull/1/commits/8c52e3d4e1ea3758e697150444ae9d40209a4434

**Comment by PMahern** [comment]
That one hard coded color isn't a problem considering you're replacing like 5 other ones. In the future it'd be nice to have a switch so you can apply multiple themes but it looks a lot better than it did so I'll merge it. Thanks!

**Pull request merged**
